apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: helshabini-keyvault
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: nginx-secret
    type: Opaque
    data:
    - objectName: dbhost
      key: host
    - objectName: dbuser
      key: username
    - objectName: dbpassword
      key: password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "helshabini-keyvault"
    objects: |
      array:
        - |
          objectName: dbhost              
          objectType: secret
          objectVersion: ""
        - |
          objectName: dbuser              
          objectType: secret
          objectVersion: ""
        - |
          objectName: dbpassword              
          objectType: secret
          objectVersion: ""
    tenantId: "6305b15e-66f0-45d1-ade9-9917962a978f"